apiVersion: v1
kind: ReplicationController
metadata:
  name: vertex-rc
spec:
   replicas: 3
   selector: 
     app: vertexrcapp
     version: 2.6.1
   template:                                     
     metadata:
       labels:
          app: vertexrcapp
          version: 2.6.1
     spec:
        containers:
        - name: vertexrcapp-container
          image: nbktechnosys/myjavaimages2dec22:1
          ports: 
          - containerPort: 8080